---
- name: Installing Webserver
  hosts: appserver
  become: yes

  tasks:
    - name: ensure apache is installed
      ansible.builtin.apt:
          name: apache2
          update_cache: yes
          state: present
          