---
- name: spring-petclinic
  hosts: appserver
  become: yes

  tasks:
    - name: ensure java is installed
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
    - name: creating a directory
      ansible.builtin.file:
        path: /usr/share/springpetclinic
        state: directory
    - name: Download the url
      get_url:
        url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    - name: add user springbootuser
      ansible.builtin.user:
        name: springbootuser
        state: present
    - name: change file owner
      ansible.builtin.file:
        path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
        owner: springbootuser
        group: springbootuser
        mode: 700
        state: file
    - name: copy service file
      ansible.builtin.copy:
        src: service
        dest: /etc/systemd/system/service
    - name: enable and start service
      ansible.builtin.systemd:
        name: springpetclinic.service
        enabled: yes
        state: started